# Generated by Django 3.2.9 on 2021-11-24 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victim',
            name='city',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='state',
        ),
        migrations.AlterField(
            model_name='victim',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 11, 8, 42, 908244)),
        ),
    ]
