# Generated by Django 3.2.9 on 2021-11-24 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211124_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='available_slots',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='latitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='longitude',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 17, 17, 46, 302711)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.victim', unique=True)),
                ('assigned_volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.volunteer')),
            ],
            options={
                'unique_together': {('assigned_victim', 'assigned_volunteer')},
                'index_together': {('assigned_victim', 'assigned_volunteer')},
            },
        ),
    ]
