# Generated by Django 3.2.9 on 2021-11-24 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_victim_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='name',
            field=models.CharField(default='aaaa', max_length=30),
        ),
        migrations.AlterField(
            model_name='victim',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 17, 30, 38, 839430)),
        ),
    ]
